<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BetterConsole.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BetterConsole.Sdk\BetterConsole.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BetterConsole.Tests" />
  </ItemGroup>

</Project>
